In [1]:

import sys
  
  
print("User Current Version:-", sys.version)

User Current Version:- 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]


# What is PyTorch?

<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/download.jpg?raw=1">

PyTorch is a Python-based scientific computing package that uses the power of graphics processing units(GPU). It is also one of the preferred deep learning research platforms built to provide maximum flexibility and speed. It is known for providing two of the most high-level features; namely, tensor computations with strong GPU acceleration support and building deep neural networks on a tape-based autograd systems.

There are many existing Python libraries which have the potential to change how deep learning and artificial intelligence are performed, and this is one such library. One of the key reasons behind PyTorch’s success is it is completely Pythonic and one can build neural network models effortlessly. It is still a young player when compared to its other competitors, however, it is gaining momentum fast.

## Brief History about PyTorch

Since its release in January 2016, many researchers have continued to increasingly adopt PyTorch. It has quickly become a go-to library because of its ease in building extremely complex neural networks. It is giving a tough competition to TensorFlow especially when used for research work. However, there is still some time before it is adopted by the masses due to its still “new” and “under construction” tags.

PyTorch creators envisioned this library to be highly imperative which can allow them to run all the numerical computations quickly. This is an ideal methodology which fits perfectly with the Python programming style. It has allowed deep learning scientists, machine learning developers, and neural network debuggers to run and test part of the code in real time. Thus they don’t have to wait for the entire code to be executed to check whether it works or not.
You can always use your favorite Python packages such as NumPy, SciPy, and Cython to extend PyTorch functionalities and services when required. Now you might ask, why PyTorch? What’ so special in using it to build deep learning models?

The answer is quite simple, PyTorch is a dynamic library (very flexible and you can use as per your requirements and changes) which is currently adopted by many of the researchers, students, and artificial intelligence developers. In the recent Kaggle competition, PyTorch library was used by nearly all of the top 10 finishers.

Some of the key highlights of PyTorch includes:

__Simple Interface:__ It offers easy to use API, thus it is very simple to operate and run like Python.

__Pythonic in nature:__ This library, being Pythonic, smoothly integrates with the Python data science stack. Thus it can leverage all the services and functionalities offered by the Python environment.

__Computational graphs:__ In addition to this, PyTorch provides an excellent platform which offers dynamic computational graphs, thus you can change them during runtime. This is highly useful when you have no idea how much memory will be required for creating a neural network model.

### Why we use PyTorch in research field?

Anyone who is working in the field of deep learning and artificial intelligence has likely worked with TensorFlow before, Google’s most popular open source library. However, the latest deep learning framework – PyTorch solves major problems in terms of research work. Arguably PyTorch is TensorFlow’s biggest competitor to date, and it is currently a much favored deep learning and artificial intelligence library in the research community.


You might be thinking why we use PyTorch? I list down the three factors for that

- Using API is Easy: It is as simple as Python.
- Pyt

### CPU v/s GPU
  - CPU have fewer but more powerful compute cores, and whereas GPUs have a large number of lower-performant cores.
  - CPUs are more suited to sequential tasks and GPUs are suitable for tasks with significant parallelization.

<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/Cpu%20vs%20Gpu.png?raw=1">

### Install

<mark style="background-color: Blue">__In CPU__</mark>

__For Windows__

* Install PyTorch using conda
      conda install pytorch torchvision cpuonly -c pytorch

* Using pip
      pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        
__For Mac__

* Using conda
      conda install pytorch torchvision -c pytorch
    
* Using pip
      pip3 install torch torchvision
    
__For Linux__

* Using conda
      conda install pytorch torchvision cpuonly -c pytorch
    
* Using pip
      pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      
      
      
<mark style="background-color: Green">__In GPU__</mark>

__For Windows__

* Install PyTorch using conda cuda=9.2 and Python=3.6
      conda install pytorch torchvision cudatoolkit=9.2 -c pytorch
     
* Using conda cuda=10.1 and Python=3.6 
      conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
     
* Install Pytorch using pip cuda=9.2 and Python=3.6
      pip3 install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
     
* Using pip cuda=10.1 and Python=3.6
      pip3 install torch torchvision
     
__For Linux__

* Install PyTorch using conda cuda=9.2 and Python=3.6
      conda install pytorch torchvision cudatoolkit=9.2 -c pytorch
     
* Using conda cuda=10.1 and Python=3.6
      conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
     
* Install Pytorch using pip cuda=9.2 and Python=3.6
      pip3 install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
     
* Using pip cuda=10.1 and Python=3.6
      pip3 install torch torchvision
     
__For Mac__

* Install PyTorch using conda  for cuda=9.2 and 10.1 we can use same command and Python=3.6

      conda install pytorch torchvision -c pytorch
         # MacOS Binaries dont support CUDA, install from source if CUDA is needed
       
* Install Pytorch using pip for cuda=9.2 and 10.1 we can use same command and Python=3.6

      pip3 install torch torchvision
         # MacOS Binaries dont support CUDA, install from source if CUDA is needed
      
You have to run all these commands in __Anaconda Prompt__ , if you want to install in a notebook just put " ! " mark before the command like: !pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

For more information about Installation you can go through this site : "https://pytorch.org/"

### Tensors

Tensor is similar to Numpy's ndarray, the additional point for Tensors in we can use it in GPUs to accelerate computing.

In [ ]:
from __future__ import print_function
import torch 

__Note:__ Uninitialized matrix is declared, but doesn't contain definite known values before it is used. When we created an Unintialized matrix, whatever values were allocated inside the memory will apear as the initial values.

Construct 6x3 matrix, uninitialized:

In [ ]:
a = torch.empty(6,3)
print(a)
type(a)

tensor([[1.0194e-38, 9.9184e-39, 2.9389e-39],
        [1.0194e-38, 2.9389e-39, 9.2755e-39],
        [9.0918e-39, 1.0010e-38, 9.9184e-39],
        [1.0653e-38, 9.1837e-39, 9.6428e-39],
        [1.0010e-38, 9.1837e-39, 8.9082e-39],
        [9.2755e-39, 1.1112e-38, 0.0000e+00]])


torch.Tensor

Construct a randomly initialized matrix:

In [ ]:
a = torch.rand(4,3)
print(a)
type(a)

tensor([[0.7165, 0.1946, 0.4888],
        [0.1459, 0.6605, 0.4174],
        [0.3007, 0.9020, 0.9754],
        [0.6012, 0.2643, 0.1553]])


torch.Tensor

Construct a matrix filled zeros and of dtype long:

In [ ]:
a = torch.zeros(4,3, dtype=torch.long)
print(a)
type(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


torch.Tensor

Construct a tensor with data:

In [ ]:
a = torch.tensor([7.8, 5])
type(a)
print(a)

tensor([7.8000, 5.0000])


or we can create new tensor with existing tensor.These methods we reuse its properties of input tensor, e.g. dtype, unless new values are provided by us.

In [ ]:
a = a.new_ones(6,5, dtype=torch.double)    # new methods take in sizes
print(a)


a = torch.randn_like(a, dtype=torch.float)  # override dtype
print(a)                                    # result will be the same size

type(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6114, -0.1190, -0.7452, -1.1604, -0.4108],
        [ 0.6734, -0.2660, -0.4076,  0.1897,  0.1084],
        [-0.0336, -0.9303, -0.7899, -2.6013,  1.3584],
        [ 0.0729,  0.6460,  0.4087, -0.5378, -0.3683],
        [ 0.1475,  0.0366, -0.9053, -1.0458,  1.2596],
        [-2.2136,  1.5095, -0.4516, -1.7238,  1.4533]])


torch.Tensor

Let's get the size:

In [ ]:
print(a.size())

torch.Size([6, 5])


Note: <mark style="background-color: Yellow">torch_size</mark> is actually a tuple, so it supports all tuple operations.

### Operations

There are multiple syntaxes for operations. In the following examples, we used addition operation,

Addition: syntax1

In [ ]:
b = torch.rand(6,5)

print(a.size())
print(b.size())

torch.Size([6, 5])
torch.Size([6, 5])


In [ ]:
print(a + b)

tensor([[ 0.3613,  0.5777, -0.4670, -1.0462,  0.4782],
        [ 1.6286, -0.1482,  0.5245,  0.8467,  0.2421],
        [ 0.6059, -0.6009,  0.0957, -1.7234,  2.2453],
        [ 0.6716,  0.8039,  0.9192,  0.4599, -0.2112],
        [ 1.1217,  1.0085,  0.0574, -0.6791,  2.2592],
        [-1.4018,  2.1200, -0.3327, -1.5783,  2.0897]])


Addition: syntax2

In [ ]:
print(torch.add(a,b))

tensor([[ 0.3613,  0.5777, -0.4670, -1.0462,  0.4782],
        [ 1.6286, -0.1482,  0.5245,  0.8467,  0.2421],
        [ 0.6059, -0.6009,  0.0957, -1.7234,  2.2453],
        [ 0.6716,  0.8039,  0.9192,  0.4599, -0.2112],
        [ 1.1217,  1.0085,  0.0574, -0.6791,  2.2592],
        [-1.4018,  2.1200, -0.3327, -1.5783,  2.0897]])


Addition: providing an output as an argument

In [ ]:
result = torch.empty(6, 5)
torch.add(a, b, out=result)
print(result)

tensor([[ 0.3613,  0.5777, -0.4670, -1.0462,  0.4782],
        [ 1.6286, -0.1482,  0.5245,  0.8467,  0.2421],
        [ 0.6059, -0.6009,  0.0957, -1.7234,  2.2453],
        [ 0.6716,  0.8039,  0.9192,  0.4599, -0.2112],
        [ 1.1217,  1.0085,  0.0574, -0.6791,  2.2592],
        [-1.4018,  2.1200, -0.3327, -1.5783,  2.0897]])


Addition: in place

In [ ]:
# adds a to b
b.add_(a)
print(b)

tensor([[ 0.3613,  0.5777, -0.4670, -1.0462,  0.4782],
        [ 1.6286, -0.1482,  0.5245,  0.8467,  0.2421],
        [ 0.6059, -0.6009,  0.0957, -1.7234,  2.2453],
        [ 0.6716,  0.8039,  0.9192,  0.4599, -0.2112],
        [ 1.1217,  1.0085,  0.0574, -0.6791,  2.2592],
        [-1.4018,  2.1200, -0.3327, -1.5783,  2.0897]])


__Note:__ Any operation that mutates a tensor in-place is post-fixed with an <mark style="background-color: red">_.</mark> For example: a.copy_(b), a.b_(), will change a.

We can use standard NumPy-like indexing with all bells and whistles!

In [ ]:
print(a[:,2])

tensor([-0.7452, -0.4076, -0.7899,  0.4087, -0.9053, -0.4516])


Resizing: We can resize or reshape tensor, use <mark style="background-color: Yellow">tensor.view</mark> for that:

In [ ]:
a = torch.randn(3, 3)
b = a.view(9)
c = a.view(-1, 9)  # the size -1 is inferred from other dimensions
print(a.size(), b.size(), c.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


If you have one value tensor, use <mark style="background-color: Yellow">.item()</mark> to get the value of the Python number

In [ ]:
a = torch.randn(1)
print(a)
print(a.item())

tensor([0.2483])
0.2482965588569641


### NumPy Bridge

Converting a Torch Tensor to NumPy array and vice versa is breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

__Converting a Torch tensor to NumPy array__

In [ ]:
x = torch.ones(4)
print(x)

tensor([1., 1., 1., 1.])


In [ ]:
y = x.numpy()
print(y)

[1. 1. 1. 1.]


See how numpy array changed in value

In [ ]:
x.add_(1)
print(x)
print(y)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


__Converting NumPy array to Torch tensor__

lets see how changing the numpy array changed the Torch Tensor automatically

In [ ]:
import numpy as np
f = np.ones(4)
g = torch.from_numpy(f)
np.add(f, 1, out=f)
print(f)
print(g)

[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

__CUDA Tensors__

Tensors can be moved onto any device using the <mark style="background-color: Yellow">.to</mark> method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

## AUTOGRAD : Automatic Differentiaition

Definition - 

  - This class is an engine to calculate derivatives. It records the graph of all the operations performed on a gradient      enabled tensor and creates a acyclic graph called the dynamic computational graph(DCG).The leaves of this graph are input tensors and the roots are output tensors. Gradients are calculated by tracing the graph from the root to the leaf and multiplying every gradient in the way using the chain rule.

Let us see this in some more easy terms with some examples

## Tensor

<mark style="background-color: Yellow">torch.Tensor</mark> is the central class of the package.If we set its attribute <mark style="background-color: Yellow">.requires_grad</mark> as <mark style="background-color: dark grey">True</mark>, it starts to track all operations on it. When you finish your computation you can call <mark style="background-color: Yellow">.backward()</mark> and have all the gradients computed automatically. The gradient of this tensor will be accumulated into <mark style="background-color: Yellow">.grad</mark> attribute.

To stop a tensor from tracking history, you can call <mark style="background-color: Yellow">.detach()</mark> to detach it from the computation history, and to prevent future computation from being tracked.


To prevent tracking history(and using memory), you can also wrap the code block in with <mark style="background-color: Yellow">torch.no_grad():</mark>. This can be particularly helpful when evaluating a model because the model may have trainable parameters with <mark style="background-color: Yellow">requires_grad=True</mark>, but for which we don’t need the gradients.

There's one more class which is very important in autograd implementation - a <mark style="background-color: Yellow">Function</mark>

<mark style="background-color: Yellow">Tensor</mark> and <mark style="background-color: Yellow">Function</mark> are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a <mark style="background-color: Yellow">.grad_fn</mark> attribute that references a Function that has created the Tensor (except for Tensors created by the user - their <mark style="background-color: Yellow">grad_fn is None</mark>).

If you want to compute the derivatives, you can call <mark style="background-color: Yellow">.backward()</mark> on a <mark style="background-color: Yellow">Tensor</mark>. If <mark style="background-color: Yellow">Tensor</mark> is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to <mark style="background-color: Yellow">backward()</mark>, however if it has more elements, you need to specify a <mark style="background-color: Yellow">gradient</mark> argument that is a tensor of matching shape.

In [ ]:
import torch

Create a tensor and set requires_grad=True to track computation with it.

In [ ]:
a = torch.ones(2, 2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:

In [ ]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


b was created as a result of an operatio, so it has a <mark style="background-color: Yellow">grad_fn</mark>

In [ ]:
print(b.grad_fn)

Do more operation on b

In [ ]:
c = b * b * 3
out = c.mean()

print(c, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


<mark style="background-color: Yellow">.requires_grad_( ... )</mark>  changes an existing Tensor’s <mark style="background-color: Yellow">requires_grad</mark> flag in-place. The input flag defaults to False if not given.

In [ ]:
p = torch.randn(3, 3)
p = ((p * 3) / (p - 1))
print(p.requires_grad)
p.requires_grad_(True)
print(p.requires_grad)
q = (p * p).sum()
print(q.grad_fn)

False
True


## Gradients

Let's backdrop now. Because <mark style="background-color: magenta">out</mark> contains a single scalar, <mark style="background-color: Yellow">out.backword</mark> is equivalent to  <mark style="background-color: Yellow">out.backward(torch.tensor(1.))</mark>. 

In [ ]:
out.backward()

Print gradients d(out)/dx

In [ ]:
print(a.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of 4.5. Let’s call the out Tensor “o”. We have that 

$o= \frac{1}{4} \sum c_i $ $c_i= 3(a_i+2)^2$  and $c_i|_{a_i=1}= 27$ . 

Therefore, $\frac{\partial_0}{\partial a_i}=\frac{3(x_i+2)}{2}$, 

hence
$\frac{\partial_0}{\partial a_i}|_{a_i=1} = \frac{9}{2} = 4.5$



### Mathematically - Jacobians and vectors

Mathematically, the autograd class is just a Jacobian-vector product computing engine. A Jacobian matrix in very simple words is a matrix representing all the possible partial derivatives of two vectors. It’s the gradient of a vector with respect to another vector.

If a vector X = [x1, x2,….xn] is used to calculate some other vector f(X) = [f1, f2, …. fn] through a function f then the Jacobian matrix (J) simply contains all the partial derivative combinations as follows:

<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/jacobian-vector.png?raw=1">

Above matrix represents the gradient of f(X)with respect to X
Suppose a PyTorch gradient enabled tensors X as:
X = [x1, x2, ….. xn] (Let this be the weights of some machine learning model)
X undergoes some operations to form a vector Y
Y = f(X) = [y1, y2, …. ym]
Y is then used to calculate a scalar loss l. Suppose a vector v happens to be the gradient of the scalar loss l with respect the vector Y as follows

<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/jacob1.png?raw=1">       *The vector v is called the grad_tensor and passed to the backward() function as an argument*

To get the gradient of the loss l with respect to the weights X the Jacobian matrix J is vector-multiplied with the vector v.

<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/jac1.png?raw=1"> 

This method of calculating the Jacobian matrix and multiplying it with a vector v enables the possibility for PyTorch to feed external gradients with ease for even the non-scalar outputs.

Now let's have a look at an example of vector-Jacobian product:

In [ ]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 659.8968,  365.4067, -713.6188], grad_fn=<MulBackward0>)


Now in this case y is no longer a scalar.<mark style="background-color: Yellow">torch.autograd(torch.tensor(1.))</mark> could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to backward as argument:

In [ ]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


You can also stop autograd from tracking history on Tensors with <mark style="background-color: Yellow">.requires_grad=True</mark> either by wrapping the code block in with <mark style="background-color: Yellow">torch.no_grad()</mark>:

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


Or by using .detach() to get a new Tensor with the same content but that does not require gradients:

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


## Neural Networks

We can construct neural networks using the <mark style="background-color: Yellow">torch.nn</mark> package.

Now that you had a glimpse of autograd, nn depends on autograd to define models and differentiate them. An nn.Module contains layers, and a method forward(input)that returns the output.

For example, look at this network that classifies digit images:
<img src="https://github.com/Anand-s-cmd/Deep_learning_POCS/blob/main/pytorch_stuff/neural.png?raw=1"> 


### convnet

It is a simple feed-forward network. It takes the input,feeds it through several layers one after the other, and then finally gives the output.

A typical training procedure for a neural network is as follows:
- Define the neural network that has some learnable parameters (or weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule: <mark style="background-color: light-blue">weight = weight - learning_rate * gradient</mark>
        
### Define the network

Let's define the network:

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class network(nn.Module): #--------------------- INHERING THE nn.module from torch.nn class

    def __init__(self):
        super(network, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)#-------1 inp image * 6 filters(3.3)= 6 out images
        self.conv2 = nn.Conv2d(6, 16, 3)#-------6 inp image * 16 filters(3.3)= 16 out images
        # an affine operation: y = mx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension#-------16(6,6) 
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))          #----------> resizing with view function
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = network()
print(net)

network(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


You just have to define the <mark style="background-color: yellow">forward</mark>,  and the <mark style="background-color: yellow">backward</mark> function (where gradients are computed) is automatically defined for you using autograd. You can use any of the Tensor operations in the <mark style="background-color: yellow">forward</mark> function.

The learnable parameters of a model are returned by <mark style="background-color: yellow">net.parameters()</mark>.

In [ ]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 3, 3])


Let’s try a random 32x32 input. Note: expected input size of this net (LeNet) is 32x32. To use this net on the MNIST dataset, please resize the images from the dataset to 32x32.

In [ ]:
inp = torch.randn(1, 1, 32, 32)
out = net(inp)
print(out)

tensor([[-0.0925, -0.0211, -0.0522, -0.1359, -0.0891,  0.0101, -0.0334, -0.0502,
         -0.1534, -0.0011]], grad_fn=<AddmmBackward0>)


Zero the gradient buffers of all parameters and backprops with random gradients:

In [ ]:
net.zero_grad()
out.backward(torch.randn(1, 10))

__Note:__
<mark style="background-color: yellow">torch.nn</mark> only supports mini-batches. The entire <mark style="background-color: yellow">torch.nn</mark> package only supports inputs that are a mini-batch of samples, and not a single sample.
For example, <mark style="background-color: yellow">nn.Conv2d</mark> will take in a 4D Tensor of <mark style="background-color: yellow">nSamples x nChannels x Height x Width</mark>.
If you have a single sample, just use <mark style="background-color: yellow">input.unsqueeze(0)</mark> to add a fake batch dimension.

__At this point, we covered:__
- Defined neutral network
- Processing input and calling backward

### Loss Function

A loss function takes the (output, target) pair of inputs, and computes a value that estimates how far away the output is from the target.
There are several different loss functions under the nn package . A simple loss is: <mark style="background-color: yellow">nn.MSELoss</mark> which computes the mean-squared error between the input and the target.
    
For example:

In [ ]:
output = net(inp)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.3845, grad_fn=<MseLossBackward0>)


Now, if you follow loss in the backward direction, using its <mark style="background-color: yellow">.grad_fn</mark>attribute, you will see a graph of computations that looks like this:

input  ->   conv2d  ->   relu  ->   maxpool2d  ->   conv2d ->   relu  ->   maxpool2d
      
      -> view -> linear -> relu -> linear -> relu -> linear
      
      -> MSELoss
      
      -> loss

So, when we call <mark style="background-color: yellow">loss.backward()</mark>, the whole graph is differentiated w.r.t. the loss, and all Tensors in the graph that has requires_grad=True will have their .grad Tensor accumulated with the gradient.


For illustration, let us follow a few steps <mark style="background-color: yellow">backward</mark>:

In [ ]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

### Backprop

To backpropagate the error all we have to do is to <mark style="background-color: yellow">loss.backward()</mark>. You need to clear the existing gradients though, else gradients will be accumulated to existing gradients.


Now we shall call <mark style="background-color: yellow">loss.backward()</mark>, and have a look at conv1’s bias gradients before and after the backward.

In [ ]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0162, -0.0175,  0.0009,  0.0051, -0.0124,  0.0038])


### Update the weights

The simplest update rule used in practice is the Stochastic Gradient Descent (SGD):
    
   <mark style="background-color: yellow"> weight = weight - learning_rate * gradient </mark>
   
We can implement this using simple Python code:

In [ ]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

However, as you use neural networks, you want to use various different update rules such as SGD, Nesterov-SGD, Adam, RMSProp, etc. To enable this, we built a small package: torch.optim that implements all these methods. Using it is very simple:

In [ ]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(inp)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

Observe how gradient buffers had to be manually set to zero using <mark style="background-color:yellow">optimizer.zero_grad()</mark>. This is because gradients are accumulated as explained in the <mark style="font-color:red">Backprop</mark> section.